version: '2.1'
networks:
  network-app:

services:
  transferer:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
       - network-app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/1-create.sql
      - ./db/inserts.sql:/docker-entrypoint-initdb.d/2-inserts.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
       - network-app
